configs:
  # provider 0:阿里云 1:腾讯云 2:华为云
  - provider: 0
    name: "demo"
    accessid: ""
    accesssecret: ""
  - provider: 1
    name: "demo2"
    accessid: ""
    accesssecret: ""
  - provider: 2
    name: "demo3"
    accessid: ""
    accesssecret: ""
